apiVersion: v1
kind: Service
metadata:
  name: clearroots-web-service
  namespace: default
  labels:
    app: clearroots-web
    project: clearroots-foundation
spec:
  type: NodePort
  selector:
    app: clearroots-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
